=== Jinglever/meta-egg-layout/_manifest/meta_egg.dtd
<!-- project: 项目
name: 项目英文名
desc: 项目描述
go_module: 项目的go module名
go_version: 项目的go版本
server_type: 项目的服务类型 (HTTP|GRPC|ALL)
-->
<!ELEMENT project (domain*, database*)>
<!ATTLIST project
    name CDATA #REQUIRED
    desc CDATA #REQUIRED
    go_module CDATA #REQUIRED
    go_version CDATA #REQUIRED
    server_type (HTTP|GRPC|ALL) #REQUIRED
>
<!-- domain: 领域 -->
<!ELEMENT domain (usecase*)>
<!-- usecase: 用例
name: 用例名, 保留词：anonymous, domain
desc: 用例描述
-->
<!ATTLIST usecase
    name CDATA #REQUIRED
    desc CDATA #REQUIRED
>
<!-- database: 数据库
name: 库名
charset: 字符集
collate: 排序规则
-->
<!ELEMENT database (table+)>
<!ATTLIST database
    name CDATA #REQUIRED
    type (MySQL|TiDB) #REQUIRED
    charset CDATA "utf8mb4"
    collate CDATA #IMPLIED
>
<!-- table: 数据库表
name: 表名, 保留词：base
type: 表类型
    META: 元数据表
    DATA: 实体表
    RI: 倒排索引表
charset: 字符集
collate: 排序规则
comment: 表描述
usecase: 所属用例名, 如果不填则表示该表属于anonymous用例
handler: 是否生成该表的handler
-->
<!ELEMENT table (column+, index*, unique*)>
<!ATTLIST table
    name CDATA #REQUIRED
    type (META|DATA|RI) #REQUIRED
    charset CDATA #IMPLIED
    collate CDATA #IMPLIED
    comment CDATA #REQUIRED
    usecase CDATA #IMPLIED
    handler (true|false) "false">
<!-- column: 表字段
name: 字段名
type: 字段类型
    _ID: 默认的表主键类型 bigint(20, unsigned) primary auto_increment not null
    _FID: 默认的外链类型 bigint(20, unsigned)
    _SMT: META表的语义字段 CHAR(16)，可自定义长度
    _ME_CREATE: 创建者
    _ME_UPDATE: 更新者
    _ME_DELETE: 删除者，必须DEFAULT NULL
    _TIME_CREATE: 创建时间
    _TIME_UPDATE: 更新时间
    _TIME_DELETE: 删除时间，NULL代表未删除，必须DEFAULT NULL
length: 字段长度/数值最大位数
decimal: 仅对decimal类型的字段有用，表示小数点右边的位数
unsigned: 是否无符号数值类型
required: 是否Not Null
primary_key: 是否主键，限一个
index: 是否对字段加索引
unique: 是否对字段加唯一索引
comment: 字段描述
insert_default: 在插入记录时该字段的默认值
ri_key: 是否倒排索引的key
hidden: 在标准handler里是否对前端隐藏
filter: 是否支持filter
order: 是否支持order
-->
<!ELEMENT column (foreign_key*)>
<!ATTLIST column
    name CDATA #REQUIRED
    type (CHAR|VARCHAR|TEXT|TINYINT|SMALLINT|MEDIUMINT|INT|BIGINT|DECIMAL|DATE|DATETIME|TIMESTAMP|TIME|_ID|_FID|_SMT|_ME_CREATE|_ME_UPDATE|_ME_DELETE|_TIME_CREATE|_TIME_UPDATE|_TIME_DELETE) #REQUIRED
    length CDATA #IMPLIED
    decimal CDATA #IMPLIED
    unsigned (true|false) "false"
    required (true|false) "false"
    primary_key (true|false) "false"
    index (true|false) "false"
    unique (true|false) "false"
    comment CDATA #IMPLIED
    insert_default CDATA #IMPLIED
    ri_key (true|false) "false"
    hidden (true|false) "false"
    filter (true|false) "false"
    order (true|false) "false">
<!-- index: 联合索引，至少要有两个字段以上-->
<!ELEMENT index (index_column, index_column+)>
<!-- unique: 联合唯一索引，至少要有两个字段以上-->
<!ELEMENT unique (index_column, index_column+)>
<!-- index_column: 联合索引字段
name: 字段名
-->
<!ELEMENT index_column EMPTY>
<!ATTLIST index_column name CDATA #REQUIRED>
<!-- foreign_key: 外链
table: 外链的目标数据库表
counter: 计数对应的表字段名
ri_raw: 倒排索引key的原始字段名
auto_remove: 当链接的目标record被删除时，是否自动删除当前record
-->
<!ELEMENT foreign_key EMPTY>
<!ATTLIST foreign_key
    table CDATA #REQUIRED
    counter CDATA #IMPLIED
    ri_raw CDATA #IMPLIED
    auto_remove (true|false) "false">

=== Jinglever/meta-egg-layout/_manifest/meta-egg-layout.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project SYSTEM "meta_egg.dtd">

<project name="meta-egg-layout" desc="MetaEgg Framework Template" go_module="meta-egg-layout" go_version="1.20" server_type="ALL">
    <database name="meta-egg-layout" type="MySQL" charset="utf8mb4" collate="utf8mb4_bin">
        <!-- 实体表示例 -->
        <table name="user" type="DATA" comment="用户" handler="true">
            <column name="id" type="_ID" order="true" list="true" />
            <column name="name" type="VARCHAR" length="64" comment="用户名" unique="true" list="true" alter="true" />
            <column name="gender" type="_FID" required="true" comment="性别" filter="true" list="true" alter="true">
                <foreign_key table="gender" />
            </column>
            <column name="age" type="TINYINT" unsigned="true" required="true" comment="年龄" alter="true" />
            <column name="is_on_job" type="_BOOL" required="true" insert_default="0" comment="是否在职" alter="true" filter="true" />
            <column name="birthday" type="DATE" required="false" comment="生日" alter="true" />
            <column name="created_by" type="_ME_CREATE" required="false" comment="创建者">
                <foreign_key table="user" />
            </column>
            <column name="created_at" type="_TIME_CREATE" required="true" comment="创建时间" />
            <column name="updated_by" type="_ME_UPDATE" required="false" comment="更新者">
                <foreign_key table="user" />
            </column>
            <column name="updated_at" type="_TIME_UPDATE" required="true" comment="更新时间" />
            <column name="deleted_by" type="_ME_DELETE" comment="删除者">
                <foreign_key table="user" />
            </column>
            <column name="deleted_at" type="_TIME_DELETE2" comment="删除时间" />

            <index>
                <index_column name="is_on_job" />
                <index_column name="age" />
            </index>
        </table>
        <!-- 元数据表示例 -->
        <table name="gender" type="META" comment="性别">
            <column name="id" type="_ID" />
            <column name="sematic" type="_SMT2" length="8" required="true" comment="语义" />
            <column name="desc" type="_DESC" length="64" required="false" comment="描述" />
            <column name="deleted_at" type="_TIME_DELETE2" comment="删除时间" />
        </table>

        <!-- 关系列表表示例 (RL: 一对多关系表) -->
        <table name="user_phone" type="RL" comment="用户电话" handler="true">
            <column name="id" type="_ID" order="true" list="true" />
            <column name="user_id" type="_FID" required="true" comment="用户ID" filter="true" list="true">
                <foreign_key table="user" is_main="true" auto_remove="true" />
            </column>
            <column name="phone_number" type="VARCHAR" length="20" required="true" comment="电话号码" list="true" alter="true" />
            <column name="created_by" type="_ME_CREATE" required="false" comment="创建者">
                <foreign_key table="user" />
            </column>
            <column name="created_at" type="_TIME_CREATE" required="true" comment="创建时间" />
            <column name="deleted_by" type="_ME_DELETE" comment="删除者">
                <foreign_key table="user" />
            </column>
            <column name="deleted_at" type="_TIME_DELETE2" comment="删除时间" />

            <unique>
                <index_column name="phone_number" />
                <index_column name="deleted_at" />
            </unique>
        </table>

        <!-- 业务规则表示例 (BR: 多对多的二元关系表) -->
        <table name="user_tag" type="BR" comment="用户标签关系" handler="true">
            <column name="id" type="_ID" order="true" list="true" />
            <column name="user_id" type="_FID" required="true" comment="用户ID" filter="true" list="true">
                <foreign_key table="user" is_main="true" />
            </column>
            <column name="tag_id" type="_FID" required="true" comment="标签ID" filter="true" list="true">
                <foreign_key table="tag" is_main="true" />
            </column>
            <column name="created_by" type="_ME_CREATE" required="false" comment="创建者">
                <foreign_key table="user" />
            </column>
            <column name="created_at" type="_TIME_CREATE" required="true" comment="创建时间" />
            <column name="deleted_by" type="_ME_DELETE" comment="删除者">
                <foreign_key table="user" />
            </column>
            <column name="deleted_at" type="_TIME_DELETE2" comment="删除时间" />

            <unique>
                <index_column name="user_id" />
                <index_column name="tag_id" />
                <index_column name="deleted_at" />
            </unique>
        </table>

        <!-- 自定义标签表 -->
        <table name="tag" type="DATA" comment="标签" handler="true">
            <column name="id" type="_ID" order="true" list="true" />
            <column name="name" type="VARCHAR" length="64" required="true" comment="标签名称" list="true" />
            <column name="deleted_at" type="_TIME_DELETE2" comment="删除时间" />
        </table>
    </database>
</project>
